config/routes.rb
Rails.application.routes.draw do
  get 'contacts/index'

  authenticate :user, lambda { |u| u.admin? } do
    mount Trestle::Engine => '/admin'
  end

  devise_for :users
  root to: 'home#index'

  resources :people, only: %w[index new create update destroy edit]
  resources :locations, only: %w[index new create update destroy edit]
  resources :shows, only: %w[index new create update destroy edit show] do
    resources :roles, only: %w[edit update new create destroy]
    resources :acts, only: %w[edit update new create destroy] do
      resources :scenes, only: %w[edit update new create destroy] do
        resources :french_scenes, only: %w[edit update new create destroy]
      end
    end
  end

  get 'shows/new_from_author/:author_id', to: 'shows#new_from_author'

  resources :authors, only: %w[index new create update destroy edit show]
  resources :contacts, only: %w[index create]
  resources :abouts, only: :index
  resources :help, only: :index
end

app/models/person.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: people
#
#  id              :bigint           not null, primary key
#  age             :integer
#  email           :string
#  ethnicity       :string           default([]), is an Array
#  first_name      :string
#  gender_identity :string
#  last_name       :string
#  lgbt            :boolean          default(FALSE)
#  notes           :string
#  phone           :string
#  strong_dancer   :boolean          default(FALSE)
#  strong_singer   :boolean          default(FALSE)
#  vocal_range     :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  user_id         :bigint           not null
#
# Indexes
#
#  index_people_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Person < ApplicationRecord
  has_person_name
  belongs_to :user

  validates :first_name, :last_name, presence: true
  validates :email, uniqueness: { scope: :user }, presence: true

  def full_name
    "#{first_name} #{last_name}".strip
  end
end

app/controllers/people_controller.rb
# frozen_string_literal: true

class PeopleController < ApplicationController
  before_action :authenticate_user!

  def index
    people = current_user.people

    render locals: { people: people }
  end

  def new
    person = Person.new

    render locals: { person: person }
  end

  def update
    person = current_user.people.find(params[:id])

    if person.update(person_params)
      redirect_to people_path
    else
      render :edit, locals: { person: person }
    end
  end

  def create
    person = current_user.people.build(person_params)
    if person.save
      redirect_to people_path, notice: 'Person created successfully'
    else
      render :new, locals: { person: person }
    end
  end

  def edit
    person = current_user.people.find(params[:id])

    render locals: { person: person }
  end

  def destroy
    person = current_user.people.find(params[:id])

    person.destroy!
    redirect_to people_path, notice: 'Person successfully deleted'
  end

  def person_params
    params.require(:person).permit(:first_name, :last_name, :phone, :email, :ethnicity, :lgbt, :gender_identity,
                                   :strong_singer, :strong_dancer, :vocal_range)
  end
end

app/views/people/_form.html.haml
= simple_form_for person do |f|
  = f.input :first_name
  = f.input :last_name
  = f.input :phone
  = f.input :email
  = f.input :ethnicity, as: :select, collection: Constants.ethnicities_for_select
  = f.input :gender_identity, as: :select, collection: Constants.gender_identities_for_select
  = f.input :lgbt
  = f.input :strong_dancer
  = f.input :strong_singer
  = f.input :vocal_range
  = f.input :notes, as: :text
  = f.button :submit

app/views/people/_person.html.haml
%tr.border-b.border-gray-200.hover
  %td.py-3.px-6.text-left.whitespace-nowrap
    = person.full_name
  %td.py-3.px-6.text-left.whitespace-nowrap
    = link_to person.email, "mailto:#{person.email}"
  %td.py-3.px-6.text-left.whitespace-nowrap
    = person.phone
  %td.py-3.px-6.text-left.whitespace-nowrap
    = person.ethnicity
  %td.py-3.px-6.text-left.whitespace-nowrap
    = person.gender_identity
  %td.py-3.px-6.text-left.whitespace-nowrap
    = person.lgbt
  %td.py-3.px-6.text-left.whitespace-nowrap
    = person.strong_dancer
  %td.py-3.px-6.text-left.whitespace-nowrap
    = person.strong_singer
  %td.py-3.px-6.text-left.whitespace-nowrap
    = person.vocal_range
  %td.py-3.px-6.text-left.whitespace-nowrap
    = link_to edit_person_path(person), title: 'Edit', data: { turbo_frame: 'details' } do
      %i.fas.fa-edit
    = link_to person_path(person), method: 'delete', data: { confirm: 'Are you sure?' } do
      %i.fas.fa-trash

app/views/people/edit.html.haml
%div{ class: 'col-span-12 sm:col-span-12 md:col-span-5 lg:col-span-4 xxl:col-span-4 mx-8' }
  = turbo_frame_tag 'details' do
    .w-full.mx-auto.my-8.text-xl.font-bold
      = person.full_name
    = render partial: 'form', locals: { person: person }

app/views/people/index.html.haml
- content_for(:main) do
  .w-full.mx-auto.my-8.text-xl.font-bold{ data: { controller: 'button' } }
    %span.float-left
      People
    = link_to 'Add Person', new_person_path, class: 'btn btn-primary mb-2 lg:mr-2 lg:mb-0 float-right', data: { turbo_frame: 'details' }
  .w-full.lg.overflow-auto
    .bg-white.rounded.my-6
      .border.border-solid.border-gray-200.overflow-auto
        %table.min-w-max.w-full.table-auto
          %thead
            %tr.bg-gray-200.text-gray-600.uppercase.text-sm.leading-normal
              %th.py-3.px-6.text-left
                Name
              %th.py-3.px-6.text-left
                Email
              %th.py-3.px-6.text-left
                Phone
              %th.py-3.px-6.text-left
                Ethnicity
              %th.py-3.px-6.text-left
                Gender Identity
              %th.py-3.px-6.text-left
                LGBT
              %th.py-3.px-6.text-left
                Strong Dancer
              %th.py-3.px-6.text-left
                Strong Singer
              %th.py-3.px-6.text-left
                Vocal Range            
              %th.py-3.px-6.text-left
                Actions
          %tbody.text-gray-600.text-sm.font-light
            - people.each do |person|
              = render partial: 'person', locals: { person: person }
- content_for(:frame) do
  Hello

app/views/people/new.html.haml
%div{ class: 'col-span-12 sm:col-span-12 md:col-span-5 lg:col-span-4 xxl:col-span-4 mx-8' }
  = turbo_frame_tag 'details' do
    .w-full.mx-auto.my-8.text-xl.font-bold
      New Person
    = render partial: 'form', locals: { person: person }