config/routes.rb
Rails.application.routes.draw do
  get 'contacts/index'

  authenticate :user, lambda { |u| u.admin? } do
    mount Trestle::Engine => '/admin'
  end

  devise_for :users
  root to: 'home#index'

  resources :people, only: %w[index new create update destroy edit]
  resources :locations, only: %w[index new create update destroy edit]
  resources :shows, only: %w[index new create update destroy edit show] do
    resources :roles, only: %w[edit update new create destroy]
    resources :acts, only: %w[edit update new create destroy] do
      resources :scenes, only: %w[edit update new create destroy] do
        resources :french_scenes, only: %w[edit update new create destroy]
      end
    end
  end

  get 'shows/new_from_author/:author_id', to: 'shows#new_from_author'

  resources :authors, only: %w[index new create update destroy edit show]
  resources :contacts, only: %w[index create]
  resources :abouts, only: :index
  resources :help, only: :index
end

app/models/scene.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: scenes
#
#  id           :bigint           not null, primary key
#  description  :string
#  name         :string
#  page_numbers :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  act_id       :bigint           not null
#
# Indexes
#
#  index_scenes_on_act_id  (act_id)
#
# Foreign Keys
#
#  fk_rails_...  (act_id => acts.id)
#
class Scene < ApplicationRecord
  belongs_to :act
  has_one :show, through: :act
  has_many :role_appearances, as: :roleable, dependent: :destroy
  has_many :roles, through: :role_appearances
  has_many :french_scenes, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :act }
end

app/controllers/scenes_controller.rb
# frozen_string_literal: true

class ScenesController < ApplicationController
  layout 'plain'

  def new
    scene = act.scenes.build

    render locals: { scene: scene }
  end

  def create
    scene = act.scenes.build

    if scene.update(scene_params)
      redirect_to(edit_show_act_path(show, act))
    else
      render :new, locals: { scene: scene }
    end
  end

  def edit
    scene = act.scenes.find(params[:id])

    render locals: { scene: scene }
  end

  def update
    scene = act.scenes.find(params[:id])

    if scene.update(scene_params)
      redirect_to(edit_show_act_path(show, act))
    else
      render :edit, locals: { scene: scene }
    end
  end

  def show
    @show ||= Show.includes(:roles).find(params[:show_id])
  end

  def act
    @act ||= show.acts.find(params[:act_id])
  end

  def destroy
    scene = act.scenes.find(params[:id])
    scene.destroy
    redirect_to edit_show_act_path(show, act), notice: 'Act deleted successfully'
  end

  def scene_params
    params.require(:scene).permit(:name, :description, role_ids: [])
  end
end

app/views/scenes/_form.html.haml
%div{ data: { controller: 'select' } } 
  = simple_form_for [scene.show, scene.act, scene] do |f|
    = f.input :name, disabled: !policy(scene).edit?
    = f.input :description, as: :text, disabled: !policy(scene).edit?

    = f.association :roles, collection: scene.show.roles, disabled: !policy(scene).edit?, input_html: { multiple: true }

    - if policy(scene).edit?
      = f.button :submit, class: 'float-right my-4'

app/views/scenes/edit.html.haml
%div{ class: 'col-span-12 sm:col-span-12 md:col-span-5 lg:col-span-4 xxl:col-span-4 mx-8' }
  = turbo_frame_tag 'details' do
    .w-full.mx-auto.my-8.text-xl.font-bold
      = scene.name
      = link_to edit_show_act_path(scene.show, scene.act, page: scene.show.page_number(by: :name)), class: 'btn btn-circle btn-outline btn-sm float-right' do
        %i.fa.fa-times
      = link_to 'Delete Scene', show_act_scene_path(scene.show, scene.act, scene), method: 'delete', class: 'btn btn-sm btn-error float-right mx-2', data: { confirm: 'Are you sure you want to delete this scene?' } if policy(scene).destroy?
    = render partial: 'form', locals: { scene: scene }
    %h3.w-full.mx-auto.my-8.text-l.font-bold.clear-both
      French Scenes
      = link_to 'Add French Scene', new_show_act_scene_french_scene_path(show_id: scene.show.id, act_id: scene.act.id, scene_id: scene.id), class: 'btn btn-sm btn-secondary float-right' if policy(scene).new?
    %ul#act_list.divide-y.divide-gray-100.clear-both
      - scene.french_scenes.order(:name).each do |french_scene|
        %li.p-3.hover:bg-primary.hover:text-primary-content
          = link_to french_scene.name, edit_show_act_scene_french_scene_path(show_id: french_scene.show.id, act_id: french_scene.act.id, scene_id: french_scene.scene.id, id: french_scene.id)

app/views/scenes/new.html.haml
%div{ class: 'col-span-12 sm:col-span-12 md:col-span-5 lg:col-span-4 xxl:col-span-4 mx-8' }
  = turbo_frame_tag 'details' do
    .w-full.mx-auto.my-8.text-xl.font-bold
      New Scene
    = render partial: 'form', locals: { scene: scene }