config/routes.rb
Rails.application.routes.draw do
  get 'contacts/index'

  authenticate :user, lambda { |u| u.admin? } do
    mount Trestle::Engine => '/admin'
  end

  devise_for :users
  root to: 'home#index'

  resources :people, only: %w[index new create update destroy edit]
  resources :locations, only: %w[index new create update destroy edit]
  resources :shows, only: %w[index new create update destroy edit show] do
    resources :roles, only: %w[edit update new create destroy]
    resources :acts, only: %w[edit update new create destroy] do
      resources :scenes, only: %w[edit update new create destroy] do
        resources :french_scenes, only: %w[edit update new create destroy]
      end
    end
  end

  get 'shows/new_from_author/:author_id', to: 'shows#new_from_author'

  resources :authors, only: %w[index new create update destroy edit show]
  resources :contacts, only: %w[index create]
  resources :abouts, only: :index
  resources :help, only: :index
end

app/views/shared/_flash_notice.html.haml
- flash.each do |type, message|
  - if type == "alert"
    .bg-red-500
      .container.px-2.py-4.mx-auto.font-sans.font-medium.text-center.text-white= message
  - if type == "notice"
    .bg-green-500
      .container.px-2.py-4.mx-auto.font-sans.font-medium.text-center.text-white= message

app/views/shared/_footer.html.haml
%footer.mt-4.p-4.footer.bg-base-300.text-base-content.footer-center
  .footer-content
    %p Ghostlight Folio is Copyright © 2021 - Charles Bandes

app/views/shared/_head.html.haml
%head
  %title
    - if content_for?(:title)
      = yield :title
      |
    Ghostlight Folio
  = csrf_meta_tags
  = csp_meta_tag
  %meta{content: "width=device-width, initial-scale=1", name: "viewport"}/
  = stylesheet_pack_tag  'application', media: 'all', 'data-turbo-track': 'reload'
  = javascript_pack_tag  'application', 'data-turbo-track': 'reload'
  = favicon_link_tag asset_path('favicon.ico')

app/views/shared/_header.html.haml
%body.h-screen.flex.flex-col.overflow-scroll
  .navbar.mb-2.shadow-lg.bg-neutral.text-neutral-content.rounded-box
    .flex-none.px-2.mx-2
      = inline_svg_tag 'ghostlightfolio-linear-white.svg', size: '30px'
      = link_to 'Ghostlight Folio', root_path, class:'link text-xl tracking-tight font-black'
  
    .flex-1.px-2.mx-2
      = link_to contacts_path, class: 'px-4 btn btn-ghost btn-sm rounded-btn', title: 'Contact Me' do
        %i{ class: 'fa fa-envelope' }
      = link_to abouts_path, class: 'px-4 btn btn-ghost btn-sm rounded-btn', title: 'About' do
        %i{ class: 'fa fa-info' }
      = link_to help_index_path, class: 'px-4 btn btn-ghost btn-sm rounded-btn', title: 'Help' do
        %i{ class: 'fa fa-question' }
        
    .flex-1
      = link_to 'Shows', shows_path, class: 'btn btn-ghost btn-sm rounded-btn'
    .flex-1
      = link_to 'Authors', authors_path, class: 'btn btn-ghost btn-sm rounded-btn'

    .flex-none
      - if user_signed_in?
        = link_to 'Edit account', edit_user_registration_path, class: 'btn btn-ghost btn-sm rounded-btn mb-2 lg:mr-2 lg:mb-0'
        = link_to 'Log out', destroy_user_session_path, method: :delete, class:'btn btn-ghost btn-sm rounded-btn mb-2 lg:mb-0'
      - else
        = link_to 'Login', new_user_session_path, class:'btn btn-ghost btn-sm rounded-btn mb-2 lg:mr-2 lg:mb-0'
        = link_to 'Sign Up', new_user_registration_path, class:'btn btn-ghost btn-sm rounded-btn'

app/views/shared/_page.html.haml
%div{ class: 'grid grid-cols-12 gap-0 flex flex-col' }
  %div{ class: 'relative col-span-12 sm:col-span-12 md:col-span-7 lg:col-span-8 xxl:col-span-8 hidden md:block main_area overflow-y-scroll flex-grow' }
    = turbo_frame_tag 'main_area' do
      %main{ class: 'px-4 lg:px-10' }
        = yield(:main)
  %div{ class: 'col-span-12 sm:col-span-12 md:col-span-5 lg:col-span-4 xxl:col-span-4 mx-8 main_area overflow-y-scroll flex-grow' }
    = turbo_frame_tag 'details' do
      = yield(:frame) || 'Empty'