config/routes.rb
Rails.application.routes.draw do
  get 'contacts/index'

  authenticate :user, lambda { |u| u.admin? } do
    mount Trestle::Engine => '/admin'
  end

  devise_for :users
  root to: 'home#index'

  resources :people, only: %w[index new create update destroy edit]
  resources :locations, only: %w[index new create update destroy edit]
  resources :shows, only: %w[index new create update destroy edit show] do
    resources :roles, only: %w[edit update new create destroy]
    resources :acts, only: %w[edit update new create destroy] do
      resources :scenes, only: %w[edit update new create destroy] do
        resources :french_scenes, only: %w[edit update new create destroy]
      end
    end
  end

  get 'shows/new_from_author/:author_id', to: 'shows#new_from_author'

  resources :authors, only: %w[index new create update destroy edit show]
  resources :contacts, only: %w[index create]
  resources :abouts, only: :index
  resources :help, only: :index
end

app/models/show.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: shows
#
#  id            :bigint           not null, primary key
#  description   :string
#  genre         :string
#  name          :string
#  public_domain :boolean
#  rights_holder :string
#  show_code     :string
#  show_type     :string
#  year_written  :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class Show < ApplicationRecord
  has_many :productions, dependent: :destroy
  has_many :roles, dependent: :destroy
  has_many :credits, dependent: :destroy
  has_many :authors, through: :credits
  has_many :acts, dependent: :destroy
  has_many :scenes, through: :acts
  has_many :french_scenes, through: :scenes

  validates :name, presence: true
  validates :year_written, numericality: { only_integer: true, allow_nil: true }, length: { maximum: 4 }

  def authors_for_display
    author_array = authors.uniq.map(&:full_name)
    author_array.join(', ')
  end

  def page_number(by: :id, per: 20)
    position = Show.joins(%i[credits authors]).includes(%i[credits authors]).where("#{by} <= ?", send(by)).count
    (position.to_f / per).ceil
  end
end

app/controllers/shows_controller.rb
# frozen_string_literal: true

class ShowsController < ApplicationController
  before_action :authenticate_user!

  def index
    @q = Show.joins(%i[credits authors]).includes(%i[credits authors]).ransack(params[:q])

    shows = @q.result(distinct: true).order(:name).includes(%i[credits authors]).page(params[:page])
    render locals: { shows: shows }
  end

  def show
    @q = Show.joins(%i[credits authors]).includes(%i[credits authors]).ransack(params[:q])

    shows = @q.result(distinct: true).order(:name).includes(%i[credits authors]).page(params[:page])
    show = Show.find(params[:id])

    respond_to do |format|
      format.html { render locals: { shows: shows, show: show } }
      format.xlsx { render locals: { show: show, xlsx_author: 'Ghostlight Folio' } }
    end
  end

  def new
    show = Show.new

    render locals: { show: show }
  end

  def new_from_author
    show = Show.new
    author = Author.find(params[:author_id])
    show.authors << author

    render :new, locals: { show: show }
  end

  def update
    show = Show.find(params[:id])
    show.authors = author_records

    if show.update(show_params)
      redirect_to show_path(show, page: show.page_number(by: :name)), notice: 'Show edited successfully'
      show.broadcast_replace_to :shows
    else
      render :edit, locals: { show: show }
    end
  end

  def create
    show = Show.new(show_params)
    show.authors = author_records
    if show.save
      redirect_to show_path(show, page: show.page_number(by: :name)), notice: 'Show created successfully'
      show.broadcast_append_to :shows
    else
      render :new, locals: { show: show }
    end
  end

  def edit
    show = Show.find(params[:id])

    render locals: { show: show }
  end

  def destroy
    show = Show.find(params[:id])

    show.destroy!
    show.broadcast_remove_to :shows
    redirect_to shows_path, notice: 'Show successfully deleted'
  end

  def show_params
    params.require(:show).permit(:name, :year_written, :copyright_year, :public_domain, :show_type, :genre)
  end

  def author_records
    author_ids = params[:show][:author_ids]
    author_ids&.delete('')
    Author.where(id: author_ids)
  end
end

app/views/shows/_form.html.haml
%div{ data: { controller: 'select' } } 
  = simple_form_for show, data: { turbo_frame: '_top'} do |f|
    = f.input :name, disabled: !policy(show).edit?
    = f.association :authors, include_blank: false, disabled: !policy(show).edit?
    = f.input :show_type, as: :select, label: 'Type', collection: Constants.show_types_for_select, disabled: !policy(show).edit?
    = f.input :genre, as: :select, collection: Constants.show_genres_for_select, disabled: !policy(show).edit?
    = f.input :description, as: :text, disabled: !policy(show).edit?
    = f.input :year_written, as: :string, wrapper: :year, disabled: !policy(show).edit?, maxlength: 4
    = f.input :rights_holder, disabled: !policy(show).edit?
    = f.input :public_domain, disabled: !policy(show).edit?
    - if policy(show).edit?
      = f.button :submit, class: 'float-right my-4'
.collapse.w-full.border.rounded-box.border-base-300.collapse-arrow.my-4{ tabindex: "0" }
  .collapse-title.text-xl.font-medium
    Roles
  .collapse-content
    = link_to 'Add Role', new_show_role_path(show), class: 'btn btn-sm btn-secondary float-right' if policy(show).new?
    %ul#role_list.divide-y.divide-gray-100.clear-both
      - show.roles.order(:name).each do |role|
        %li.p-3.hover:bg-primary.hover:text-primary-content
          = link_to role.name, edit_show_role_path(show_id: show.id, id: role.id)
  
.collapse.w-full.border.rounded-box.border-base-300.collapse-arrow.my-4{ tabindex: "0" }
  .collapse-title.text-xl.font-medium
    Acts and Scenes
  .collapse-content
    = link_to 'Add Act', new_show_act_path(show), class: 'btn btn-sm btn-secondary float-right' if policy(show).new?
    %ul#act_list.divide-y.divide-gray-100.clear-both
      - show.acts.order(:name).each do |act|
        %li.p-3.hover:bg-primary.hover:text-primary-content
          = link_to act.name, edit_show_act_path(show_id: show.id, id: act.id)

app/views/shows/_show.html.haml
%tr.hover{ id: dom_id(show), data: { action: 'click->table-row#click', link: edit_show_path(show) } }
  %td
    = show.name
  %td
    = show.authors_for_display
  %td
    = Constants::SHOW_TYPES[show.show_type&.to_sym]
  %td
    = Constants::SHOW_GENRES[show.genre&.to_sym]
  %td
    = show.year_written
  %td
    = inline_svg_tag 'check.svg' if show.public_domain

app/views/shows/edit.html.haml
%div{ class: 'col-span-12 sm:col-span-12 md:col-span-5 lg:col-span-4 xxl:col-span-4 mx-8 main_area overflow-y-scroll' }
  = turbo_frame_tag 'details' do
    .w-full.mx-auto.my-8.text-xl.font-bold
      = show.name
    = link_to 'Delete Show', show_path(show), method: 'delete', class: 'btn btn-sm btn-error float-right', data: { confirm: 'Are you sure you want to delete this show? All roles will also be deleted.' } if policy(show).destroy?
    = link_to show_path(show, format: 'xlsx'), title: 'Download excel spreadsheet', class: 'btn btn-sm btn-outline float-right mx-2' do
      %i.fa.fa-file-excel
    - show.authors.each do |author|
      .btn.btn-sm.btn-outline.my-1
        = link_to author.full_name, author_path(author, page: author.page_number(by: :last_name)), data: { turbo_frame: '_top' }
    = render partial: 'form', locals: { show: show }

app/views/shows/index.html.haml
- content_for(:main) do
  .w-full.mx-auto.my-8.text-xl.font-bold
    %h2.float-left
      Shows
    %label#advanced_search_link{ for: "search-modal", class: "btn btn-primary modal-button float-right", title: 'Search' }
      %i.fa.fa-search.mx-2          
    %input{ type: "checkbox", id: "search-modal", class: "modal-toggle", style: 'display: none' } 
    .modal.clearfix
      = search_form_for @q, data: { turbo_frame: '_top' } do |f|
        .modal-box.text-sm.font-light{ data: { controller: 'select' } }
          %h2.text-lg.font-bold
            %i.fa.fa-search.mx-2          
            Search
          %ul.clearfix
            %li.search-row.my-4.block#show_name
              = f.label :name_cont, 'Show name', class: 'search-label'
              = f.search_field :name_cont, class: 'input input-bordered search-field ml-4'
            %li.search-row.my-4.block#show_name
              = f.label :credits_author_first_name_cont, 'Author first name', class: 'search-label'
              = f.search_field :credits_author_first_name_cont, class: 'input input-bordered search-field ml-4'
            %li.search-row.my-4.block#show_name
              = f.label :credits_author_last_name_cont,  'Author last name', class: 'search-label'
              = f.search_field :credits_author_last_name_cont, class: 'input input-bordered search-field ml-4'
            %li.search-row.my-4.block#author_ethnicity
              = f.label :credits_author_ethnicity_contains, 'Author ethnicity', class: 'search-label'
              = f.select :credits_author_ethnicity_contains, Constants.ethnicities_for_select, include_blank: true, class: 'search-field'
            %li.search-row.my-4.block#author_gender_identity
              = f.label :credits_author_gender_identity_eq, 'Author gender identity', class: 'search-label'
              = f.select :credits_author_gender_identity_eq, Constants.gender_identities_for_select, include_blank: true, class: 'search-field'
            %li.search-row.my-4.block#author_lgbt
              = f.label :credits_author_lgbt_eq, 'Author LGBT?', class: 'search-label'
              = f.select :credits_author_lgbt_eq, [['Yes', 1], ['No', 0]], include_blank: true, class: 'search-field'
            %li.search-row.my-4.block
              = f.label :show_type_eq, 'Show type', class: 'search-label'
              = f.select :show_type_eq, Constants.show_types_for_select, include_blank: true, class: 'search-field'
            %li.search-row.my-4.block
              = f.label :genre_eq, 'Show genre', class: 'search-label'
              = f.select :genre_eq, Constants.show_genres_for_select, include_blank: true, class: 'search-field'
            %li.search-row.my-4.block#public_domain
              = f.label :public_domain_eq, 'Public Domain?', class: 'search-label'
              = f.select :public_domain_eq, [['Yes', 1], ['No', 0]], include_blank: true, class: 'search-field'
          .modal-action.clear-both
            %label{ for: "search-modal", class: "btn btn-outline btn-sm float-right" }
              Cancel
            = f.submit class: 'btn btn-primary btn-sm float-right'
    = link_to 'Add Show', new_show_path, class: 'btn btn-primary mb-2 lg:mr-2 lg:mb-0 float-right', data: { turbo_frame: 'details' } if policy(shows).edit?
  .w-full.lg.overflow-auto
    .bg-white.rounded.my-6
      = turbo_stream_from :shows
      %table.table.table-zebra.w-full.table-compact{ data: { controller: 'table-row' } }
        %thead
          %th
            %a{ href: sort_url(@q, :name), data: { turbo_frame: '_top' } }
              Name
          %th
            %a{ href: sort_url(@q, 'credits_author_last_name'), data: { turbo_frame: '_top' } }
              Author
          %th
            %a{ href: sort_url(@q, :show_type), data: { turbo_frame: '_top' } }
              Type
          %th
            %a{ href: sort_url(@q, :genre), data: { turbo_frame: '_top' } }
              Genre
          %th
            %a{ href: sort_url(@q, :year_written), data: { turbo_frame: '_top' } }
              Year Written
          %th
            %a{ href: sort_url(@q, :public_domain), data: { turbo_frame: '_top' } }
              Public Domain
        %tbody
          - shows.each do |show|
            = render partial: 'show', locals: { show: show }
  = paginate shows

app/views/shows/new.html.haml
%div{ class: 'col-span-12 sm:col-span-12 md:col-span-5 lg:col-span-4 xxl:col-span-4 mx-8' }
  = turbo_frame_tag 'details' do
    .w-full.mx-auto.my-8.text-xl.font-bold
      New Show
    %div{ data: { controller: 'select' } } 
      = simple_form_for show, data: { turbo_frame: '_top'} do |f|
        = f.input :name, disabled: !policy(show).edit?
        = f.association :authors, include_blank: false, disabled: !policy(show).edit?
        = f.input :show_type, as: :select, label: 'Type', collection: Constants.show_types_for_select, disabled: !policy(show).edit?
        = f.input :genre, as: :select, collection: Constants.show_genres_for_select, disabled: !policy(show).edit?
        = f.input :description, as: :text, disabled: !policy(show).edit?
        = f.input :year_written, as: :string, wrapper: :year, disabled: !policy(show).edit?, maxlength: 4
        = f.input :rights_holder, disabled: !policy(show).edit?
        = f.input :public_domain, disabled: !policy(show).edit?
        - if policy(show).edit?
          = f.button :submit, class: 'float-right my-4'

app/views/shows/show.html.haml
- content_for(:main) do
  .w-full.mx-auto.my-8.text-xl.font-bold
    %span.float-left
      Shows
    %label#advanced_search_link{ for: "search-modal", class: "btn btn-primary modal-button float-right", title: 'Search' }
      %i.fa.fa-search.mx-2     
    %input{ type: "checkbox", id: "search-modal", class: "modal-toggle", style: 'display: none' } 
    .modal
      = search_form_for @q, data: { turbo_frame: '_top' } do |f|
        .modal-box.text-sm.font-light{ data: { controller: 'select' } }
          %h2.text-lg.font-bold
            %i.fa.fa-search.mx-2          
            Search
          %ul.clearfix
            %li.search-row.my-4.block#show_name
              = f.label :name_cont, 'Show name', class: 'search-label'
              = f.search_field :name_cont, class: 'input input-bordered search-field ml-4'
            %li.search-row.my-4.block#show_name
              = f.label :credits_author_first_name_cont, 'Author first name', class: 'search-label'
              = f.search_field :credits_author_first_name_cont, class: 'input input-bordered search-field ml-4'
            %li.search-row.my-4.block#show_name
              = f.label :credits_author_last_name_cont,  'Author last name', class: 'search-label'
              = f.search_field :credits_author_last_name_cont, class: 'input input-bordered search-field ml-4'
            %li.search-row.my-4.block#author_ethnicity
              = f.label :credits_author_ethnicity_contains, 'Author ethnicity', class: 'search-label'
              = f.select :credits_author_ethnicity_contains, Constants.ethnicities_for_select, include_blank: true, class: 'search-field'
            %li.search-row.my-4.block#author_gender_identity
              = f.label :credits_author_gender_identity_eq, 'Author gender identity', class: 'search-label'
              = f.select :credits_author_gender_identity_eq, Constants.gender_identities_for_select, include_blank: true, class: 'search-field'
            %li.search-row.my-4.block#author_lgbt
              = f.label :credits_author_lgbt_eq, 'Author LGBT?', class: 'search-label'
              = f.select :credits_author_lgbt_eq, [['Yes', 1], ['No', 0]], include_blank: true, class: 'search-field'
            %li.search-row.my-4.block
              = f.label :show_type_eq, 'Show type', class: 'search-label'
              = f.select :show_type_eq, Constants.show_types_for_select, include_blank: true, class: 'search-field'
            %li.search-row.my-4.block
              = f.label :genre_eq, 'Show genre', class: 'search-label'
              = f.select :genre_eq, Constants.show_genres_for_select, include_blank: true, class: 'search-field'
            %li.search-row.my-4.block#public_domain
              = f.label :public_domain_eq, 'Public Domain?', class: 'search-label'
              = f.select :public_domain_eq, [['Yes', 1], ['No', 0]], include_blank: true, class: 'search-field'
          .modal-action.clear-both
            %label{ for: "search-modal", class: "btn btn-outline btn-sm float-right" }
              Cancel
            = f.submit class: 'btn btn-primary btn-sm float-right'
    = link_to 'Add Show', new_show_path, class: 'btn btn-primary mb-2 lg:mr-2 lg:mb-0 float-right', data: { turbo_frame: 'details' } if policy(show).edit?
  .w-full.lg.overflow-auto
    .bg-white.rounded.my-6
      %table.table.table-zebra.table-compact.w-full{ data: { controller: 'table-row', highlighted_row: "show_#{show.id}" } }
        %thead
          %th
            %a{ href: sort_url(@q, :name), data: { turbo_frame: '_top' } }
              Name
          %th
            %a{ href: sort_url(@q, :credits_author_last_name), data: { turbo_frame: '_top' } }
              Author
          %th
            %a{ href: sort_url(@q, :show_type), data: { turbo_frame: '_top' } }
              Type
          %th
            %a{ href: sort_url(@q, :genre), data: { turbo_frame: '_top' } }
              Genre
          %th
            %a{ href: sort_url(@q, :year_written), data: { turbo_frame: '_top' } }
              Year Written
          %th
            %a{ href: sort_url(@q, :public_domain), data: { turbo_frame: '_top' } }
              Public Domain
        %tbody
          - shows.each do |show_item|
            = render partial: 'show', locals: { show: show_item }
      = paginate shows
- content_for(:frame) do
  .w-full.mx-auto.my-8.text-xl.font-bold
    = show.name
  = link_to 'Delete Show', show_path(show), method: 'delete', class: 'btn btn-sm btn-error float-right', data: { confirm: 'Are you sure you want to delete this show? All roles will also be deleted.' } if policy(show).destroy?
  = link_to show_path(show, format: 'xlsx'), title: 'Download excel spreadsheet', class: 'btn btn-sm btn-outline float-right mx-2' do
    %i.fa.fa-file-excel
  - show.authors.each do |author|
    .btn.btn-sm.btn-outline.my-1
      = link_to author.full_name, author_path(author, page: author.page_number(by: :last_name)), data: { turbo_frame: '_top' }

  = render partial: 'form', locals: { show: show }